### PR TITLE
Simplified panel.sh

### PR DESCRIPTION
**Pull request by yesBad**
This will work if they have 1.3.2 or higher which everyone should have :D

### CODE REVIEW

**Comment by hwalker928** [comment]
Closing due to the updater command bug right now. I recall a bug about using the command, and running it just failed for me anyway.

**Comment by yesBad** [comment]
> Closing due to the updater command bug right now.

What bug?

**Comment by hwalker928** [comment]
> > Closing due to the updater command bug right now.
> 
> What bug?

https://github.com/pterodactyl/panel/issues/3535

**Comment by yesBad** [comment]
> > > Closing due to the updater command bug right now.
> > 
> > 
> > What bug?
> 
> [pterodactyl/panel#3535](https://github.com/pterodactyl/panel/issues/3535)
chrome_UprBGz4fJp

Latest is 1.6 tho

**Comment by hwalker928** [comment]
The current method works just fine, and also the issue would have been closed if it was fixed.

**Comment by yesBad** [comment]
> The current method works just fine, and also the issue would have been closed if it was fixed.

The command works for me fine, and never faced issues. /shrug

**Comment by BetTD** [comment]
@yesBad Doing it the "manual" way allows us to track each step of the process and also gives us the option to add error checks in the near future to avoid bricking an installation. I understand that the self-updater command is quite convenient, but it just doesn't give us the same degree of control that running each command manually would (e.g. checking exit codes). Maybe the command will improve in the future, but for now we feel like this is the way to go.

I really appreciate that you took the time to contribute to the project though.

**Comment by yesBad** [comment]
Understandable. Tho I'm still wondering about the bricking thing. Ive never used manual upgrade after the release of that one liner. Never had bricked my install.

**Comment by BetTD** [comment]
Harry will probably have to explain a bit more, I've never used that command before.

@hwalker928

**Comment by hwalker928** [comment]
> Harry will probably have to explain a bit more, I've never used that command before.
> 
> @hwalker928 

it's been disabled by upstream

**Pull request closed without merging**
